
- name: "Add datastax repo key"
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch 

- name: "Configura repositorio do elasticsearch"
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main"

- name: "Configura repositorio do logstash"
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/1.4/debian stable main"

- name: "Instala elasticsearch"
  apt: name=elasticsearch state=latest update_cache=yes install_recommends=yes

- name: "Instala logstash"
  apt: name=logstash state=latest install_recommends=yes

- name: "Adiciona logstash.conf"
  template: src=logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf

- name: "Adiciona logstash-frontend service"
  template: src=logstash-frontend dest=/etc/init.d mode=0751

- name: "Adiciona elasticsearch.yml"
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml

- name: "reinicia elasticsearch"
  service: name=elasticsearch state=restarted

- name: "reinicia logstash"
  service: name=logstash state=restarted

- name: "inicia logstash web frontend"
  service: name=logstash-frontend state=started


