- hosts: localhost
  connection: local

  tasks:
  - name: "Cria security group"
    ec2_group: 
      name: cassandra_group
      description: "Cassandra Security group"
      vpc_id: "{{vpc_id}}"
      region: "{{aws_region}}"
      rules:
        - proto: tcp
          type: ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

        - proto: tcp
          type: http
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        
        - proto: tcp
          type: Custom TCP Rule
          from_port: 1024
          to_port: 65535
          cidr_ip: "{{ cidr_ip }}"
        
        - proto: tcp
          type: Custom TCP Rule
          from_port: 7000
          to_port: 7200
          cidr_ip: "{{ cidr_ip }}"

      rules_egress:
        - proto: all
          type: all
          cidr_ip: 0.0.0.0/0
    register: ec2_firewall

  - name: "Cria instancias no EC2 para o cluster"
    local_action: ec2 key_name="{{ssh_key_name}}"
      count="{{ vm_count }}" 
      vpc_subnet_id="{{subnet_id}}"
      region="{{aws_region}}"
      group_id="{{ec2_firewall.group_id}}"
      instance_type="{{instance_type}}"
      image="{{ami_id}}"
      wait=yes
      assign_public_ip=yes
    register: ec2

  - name: "Adiciona host ao grupo instancias" 
    add_host: hostname={{ item.public_ip }} groupname=instancias
    with_items: ec2.instances

  - name: "Cria a variável seeds com os IPs privados das instâncias"
    add_host: hostname={{ item.private_ip}} groupname=private_ips
    with_items: ec2.instances

  - name: "Espera confirmação antes de seguir, verificando a porta 22"
    wait_for: port=22 host="{{ item.public_ip }}" search_regex=OpenSSH delay=10 
    with_items: ec2.instances

# Cria o cluster de cassandra
- hosts: instancias
  sudo: True
  user: ubuntu
  gather_facts: True
  vars:
    - java_versions: oracle-java7-installer
    - cluster_name: "Cassandra Cluster AWS"
    - snitch: Ec2Snitch
    - seeds: "{{ groups['private_ips'] | join(',') }}"
  roles:
    - common
    - python
    - java
    - cassandra

