# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = '2'.freeze

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define 'blog' do |blog|
    blog.vm.box = 'ubuntu/trusty64'
    blog.vm.network :private_network, ip: '192.168.33.21'

    blog.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'blog.yml'
      ansible.verbose = 'vvv'
    end

    config.vm.provider 'virtualbox' do |vbox|
      vbox.memory = '1024'
    end
  end
end
