# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = '2'.freeze

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define 'testvm' do |testvm|
    testvm.vm.box = 'ubuntu/trusty64'
    testvm.vm.network :private_network, ip: '192.168.33.21'

    testvm.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'webserver.yml'
      ansible.verbose = 'vvv'
    end

    config.vm.provider 'virtualbox' do |vbox|
      vbox.memory = '1024'
    end
  end
end
