---
# lxc-docker is the default
docker_pkg_name: lxc-docker
# docker_pgk_name: docker.io
# Change these to 'present' if you're running Ubuntu 12.04-13.10 and are fine with less-than-latest packages
kernel_pkg_state: latest
cgroup_lite_pkg_state: latest
# Important if running Ubuntu 12.04-13.10 and ssh on a non-standard port
ssh_port: 22
# Place to get apt repository key
apt_key_url: http://get.docker.io/gpg
# apt repository key signature
apt_key_sig: A88D21E9
# Name of the apt repository for docker
apt_repository: deb http://get.docker.io/ubuntu docker main
# The following help expose a docker port or to add additional options when running docker
# The default is to not use any special options; see docker_opts
#docker_host_ip: 0.0.0.0
#docker_host_port: 2375
docker_opts: ""
#docker_opts: "-H unix:// -H tcp://{{ docker_host_ip }}:{{ docker_host_port }}"
#docker_version: 1.2.0
# Want to export the docker host?  You'll need to uncomment the docker_host_ip, port, opts
export_docker_host: false