- hosts: all
  connection: local
  user: ubuntu

  tasks:
    - name: "Cria a maquina web"
      digital_ocean: state=present 
        command=droplet 
        name=wordpress-web
        size_id={{ do_size_id }}
        region_id={{ do_region_id }}
        image_id={{ do_image_id }}
        ssh_key_ids={{ do_ssh_key_ids }}
        virtio=yes
      register: web

    - name: "Cria a maquina db"
      digital_ocean: state=present 
        command=droplet 
        name=wordpress-db
        size_id={{ do_size_id }}
        region_id={{ do_region_id }}
        image_id={{ do_image_id }}
        ssh_key_ids={{ do_ssh_key_ids }}
        virtio=yes
      register: db

    - name: "Espera confirmação antes de seguir, verificando a porta 22"
      wait_for: port=22 host="{{ web.droplet.ip_address }}" search_regex=OpenSSH delay=30

    - name: "Espera confirmação antes de seguir, verificando a porta 22"
      wait_for: port=22 host="{{ db.droplet.ip_address }}" search_regex=OpenSSH delay=30

    - name: "Id da máquina web"
      debug: msg="{{ web.droplet.id }}"

    - name: "IP da máquina web"
      debug: msg="{{ web.droplet.ip_address }}"

    - name: "Id da máquina db"
      debug: msg="{{ db.droplet.id }}"

    - name: "IP da máquina db"
      debug: msg="{{ db.droplet.ip_address }}"

    - name: "Adiciona host ao grupo instancias web"
      add_host: hostname={{ web.droplet.ip_address }} groupname=instancias_web

    - name: "Adiciona host ao grupo instancias db"
      add_host: hostname={{ db.droplet.ip_address }} groupname=instancias_db

- hosts: instancias_web
  sudo: True
  user: root
  roles:
    - common
    - php
    - nginx
    - wordpress

- hosts: instancias_db
  sudo: True
  user: vagrant
  vars_files:
    - vars/mysql.yml
  roles:
    - common
    - mysql
