# Cria uma máquina
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: "Cria security group"
    ec2_group: 
      name: cassandra_group
      description: "Cassandra Security group"
      vpc_id: "{{vpc_id}}"
      region: "{{aws_region}}"
      rules:
        - proto: tcp
          type: ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          type: http
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          type: all
          cidr_ip: 0.0.0.0/0
    register: ec2_firewall

  - name: "Cria uma instancia no EC2"
    local_action: ec2 key_name="{{ssh_key_name}}"
      vpc_subnet_id="{{subnet_id}}"
      region="{{aws_region}}"
      group_id="{{ec2_firewall.group_id}}"
      instance_type="{{instance_type}}"
      image="{{ami_id}}"
      wait=yes
      assign_public_ip=yes
    register: ec2

  - name: "Adiciona host ao grupo instancias" 
    add_host: hostname={{ item.public_ip }} groupname=instancias
    with_items: ec2.instances

  - name: "Espera confirmação antes de seguir, verificando a porta 22"
    wait_for: port=22 host="{{ item.public_ip }}" search_regex=OpenSSH delay=10 
    with_items: ec2.instances

# Usando a máquina que criamos, vamos instalar o NGINX.
- hosts: instancias
  sudo: True
  user: ubuntu
  gather_facts: True
  tasks:
    - name: "Atualiza pacotes e instala nginx"
      apt: name=nginx state=latest update_cache=yes install_recommends=yes


