- name: "Atualiza pacotes e instala nginx"
  apt: name=nginx state=latest update_cache=yes install_recommends=yes

- name: "Copia configuração de blog.nginx para /etc/nginx/sites-available/blog"
  template: src=blog.nginx dest=/etc/nginx/sites-available/blog 

- name: "Apaga o site default"
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: "Ativa o site"
  file: src=/etc/nginx/sites-available/blog dest=/etc/nginx/sites-enabled/blog state=link
   
- name: "Reinicia NGINX"
  service: name=nginx state=restarted
    
